### ISSUE TITLE
Problems when importing Table

### ISSUE THREAD

**Issue by mlallenAxpe** [Telefonica/mistica-web#1159]
**Describe the bug**
When I attempt to import the Table module and reproduce it in a page, I receive an error message that states `Attempted import error: 'Table' is not exported from '@telefonica/mistica'.`

**To Reproduce** 

1. Create a web project.
2. Install '@telefonica/mistica' node module.
3. Import the Table module from '@telefonica/mistica'.
4. Add Table as a component

**Expected behavior**
It should show a table similar to this one:
![Screenshot 2024-06-27 at 10 30 42](https://github.com/Telefonica/mistica-web/assets/122606315/720e7784-0b23-4300-8ba1-56d2b8ce0a4a)

**Screenshots**
![Screenshot 2024-06-27 at 10 32 50](https://github.com/Telefonica/mistica-web/assets/122606315/3bc4cc9d-21f1-4909-be24-9112a0c59b8c)

**Desktop (please complete the following information):**

- OS: macOS Sonoma
- Browser: Chrome
- Version 126.0.6478.116

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone11]
- OS: [e.g. iOS13]
- Version [e.g. 84]

**Comment by marcoskolodny** [comment]
We've reviewed with Miguel offline, and it looks like it may have been something related to cache. Now it's working as expected

**Comment by jmartinpizarro** [comment]
I've been working with Mistica and I am currently having the same problem related with the table component.

**Describe the bug**
When I attempt to import the Table module and reproduce it in a page, I receive an error message that states Attempted import error: 'Table' is not exported from '@telefonica/mistica'.

**To Reproduce**

    1. Create a web project.
    2. Install '@telefonica/mistica' node module.
    3. Import the Table module from '@telefonica/mistica'.
    4. Add Table as a component

**Expected behavior**

![imagen](https://github.com/user-attachments/assets/b5ecd60e-47ca-4077-9ae7-53241bfe8283)

**Error obtained**:
<img width="1076" alt="Captura de pantalla 2024-08-16 a las 9 38 39" src="https://github.com/user-attachments/assets/76e2143b-6232-48fc-adef-e636abf41849">

**Solutions tried**: something similar as in the following example provided
- Deleting cache of the browser (the solution mentioned in the previous comment). However, it did not work.

**Desktop (please complete the following information):**

    - OS: macOS Ventura
    - Browser: Firefox
    - Version 129.0.1
