### ISSUE TITLE
NextJS 13 example

### ISSUE THREAD

**Issue by jalaguerom** [Telefonica/mistica-web#605]
I am migrating a React app to a NextJS app. I try to use new NextJS 13 and experimental appDir but I get an error only in dev mode which says:
`Warning: Prop 'className' did not match. Server: "mistica-11-12-2_0_layout-5-3-2" Client: "mistica-11-12-2_0_layout-0-3-2"`
This error is thrown when I use a ResponsiveLayout. I followed NextJS 12 example and the error is not thrown. Can you please create an example using appDir and NextJS 13?

**Comment by atabel** [comment]
Hi, @jalaguerom, we have some issues with SSR (and hydration missmatches) in mistica, most of them are caused by the css in js lib we were using (JSS).

[We are in the process to migrate our styling solution to vanilla extract](https://github.com/Telefonica/mistica-web/issues/571), which has much better support for SSR and we want to solve all these problems. Once we finish the migration we'll probably release a major version of mistica with some breaking changes. Our idea is making that major version fully compatible with React 18 and SSR, so probably you won't have issues with Next 13 either. Of course, we'll be able to update our Next example then.

Meanwhile, if you want we can discuss (in Teams) some posible workarounds for your case. We have some Next 12 webs using SSR right now, so maybe the workarounds we have used may fix your issues too
